services:
  minio:
    image: minio/minio:latest
    container_name: pdf-accessibility-minio
    ports:
      - "9010:9000"      # API
      - "9011:9001"      # Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    volumes:
      - minio_data:/data
      - ./scripts:/scripts
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  # MinIO Client para configuração inicial
  minio-client:
    image: minio/mc:latest
    container_name: pdf-accessibility-minio-client
    depends_on:
      - minio
    volumes:
      - ./scripts:/scripts
    entrypoint: >
      /bin/sh -c "
      until /usr/bin/mc alias set myminio http://minio:9000 minioadmin minioadmin123; do
        echo 'Waiting for MinIO to be ready...';
        sleep 1;
      done;
      /usr/bin/mc mb myminio/pdf --ignore-existing;
      /usr/bin/mc mb myminio/temp --ignore-existing;
      /usr/bin/mc mb myminio/html-reports --ignore-existing;
      /usr/bin/mc policy set public myminio/pdf;
      /usr/bin/mc policy set public myminio/html-reports;
      /usr/bin/mc policy set public myminio/temp;
      echo 'MinIO buckets configured successfully!';
      "

volumes:
  minio_data:
    driver: local
