services:
  # Upload de todos os PDFs da pasta samples para MinIO existente
  a11y-ai-pdf-checker-pdf-uploader:
    image: amazon/aws-cli:latest
    container_name: a11y-ai-pdf-checker-pdf-uploader
    environment:
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin123
      AWS_DEFAULT_REGION: us-east-1
    volumes:
      - ./samples:/samples:ro
    entrypoint: >
      /bin/sh -c "
      echo 'Fazendo upload de todos os PDFs da pasta samples para MinIO...';
      echo 'Arquivos encontrados:';
      ls -la /samples/*.pdf 2>/dev/null || echo 'Nenhum arquivo PDF encontrado';
      echo '';
      for pdf in /samples/*.pdf; do
        if [ -f \"\$$pdf\" ]; then
          filename=\$$(basename \"\$$pdf\")
          echo \"Enviando \$$filename...\";
          aws --endpoint-url http://host.docker.internal:9010 s3 cp \"\$$pdf\" s3://pdf/\$$filename;
          echo \"\$$filename enviado ✓\";
        fi
      done;
      echo '';
      echo 'Upload concluído!';
      "
    network_mode: host

  # Container de teste principal
  a11y-ai-pdf-checker-accessibility-tester:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: a11y-ai-pdf-checker-test-runner
    depends_on:
      a11y-ai-pdf-checker-pdf-uploader:
        condition: service_completed_successfully
    environment:
      ENVIRONMENT: local
      MINIO_ENDPOINT: http://host.docker.internal:9010
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
    volumes:
      - ./reports:/app/reports
    command: python3 test_runner.py
    network_mode: host
